"""origin id

Revision ID: 369dbb523c01
Revises: a430f876d310
Create Date: 2025-11-21 18:39:20.231650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369dbb523c01'
down_revision: Union[str, None] = 'e53fbac2bc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_23377_sqlite_autoindex_categories_1'), table_name='categories')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.add_column('items', sa.Column('origin_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('idx_23382_ix_items_name'), table_name='items')
    op.create_index(op.f('ix_items_origin_id'), 'items', ['origin_id'], unique=True)
    op.drop_index(op.f('idx_23387_ix_price_history_item_id'), table_name='price_history')
    op.drop_constraint(op.f('price_history_item_id_fkey'), 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'items', ['item_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('price_history_item_id_fkey'), 'price_history', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_23387_ix_price_history_item_id'), 'price_history', ['item_id'], unique=False)
    op.drop_index(op.f('ix_items_origin_id'), table_name='items')
    op.create_index(op.f('idx_23382_ix_items_name'), 'items', ['name'], unique=True)
    op.drop_column('items', 'origin_id')
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('idx_23377_sqlite_autoindex_categories_1'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###
