"""rm image column

Revision ID: 9134877f5660
Revises: 20240603_fts_items_sync
Create Date: 2025-06-15 21:36:40.124280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9134877f5660'
down_revision: Union[str, None] = '20240603_fts_items_sync'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
